Us 3
TMDAD-Chat/user-api pull request #2
Opened 2022-04-03 16:57 UTC by lAngelP

2022-04-04 21:26 UTC, FreddyMartinez requested changes

2022-04-04 21:26 UTC, FreddyMartinez commented on src/main/java/es/unizar/tmdad/dto/UserDto.java
> +    private String name;
a lo mejor vale la pena dejarle el id o ponerle email

2022-04-04 21:26 UTC, FreddyMartinez commented on src/main/java/es/unizar/tmdad/service/impl/RoomServiceImpl.java
> +        }
aquí hay algo que no me queda claro: envías el usuario que quieres añadir o eliminar, luego obtienes las entidades de ese usuario y del propietario de la sala de chat. Si ese usuario y el propietario no son el mismo, lanzas la excepción?  luego, si son el mismo, estarías añadiendo o eliminando al propietario de la sala, no? :thinking:

2022-04-05 05:58 UTC, lAngelP commented on src/main/java/es/unizar/tmdad/service/impl/RoomServiceImpl.java
> +        }
Un usuario X pide añadir a un usuario Y a la sala. Se comprueba que ambos existan en la DB, que X sea el dueño de la sala (quien la creó). Si eso es correcto, se añade al usuario Y a la sala (o se borra de ella).

Se lanzan las excepciones por que más adelante las customizaremos y le diremos a Spring que si las detecta no devuelva un código 200 o 500, sino un 4xx, según el caso

2022-04-05 05:59 UTC, lAngelP commented on src/main/java/es/unizar/tmdad/dto/UserDto.java
> +    private String name;
El identificador realmente es el nombre del usuario. Lo he dejado en mínimos para ir completando y ampliando después de la entrega del 7. Por mi parte no hay problema en ampliar los campos

2022-04-05 19:30 UTC, FreddyMartinez commented on src/main/java/es/unizar/tmdad/service/impl/RoomServiceImpl.java
> +        }
vale, no me hagas caso, la sentencia `!Objects.equals(room.getOwner(), owner)` la leí como `!Objects.equals(user, owner)`. Le echaré la culpa al cansancio, sorry :3

2022-04-05 19:31 UTC, FreddyMartinez approved these changes

2022-04-06 04:15 UTC, merged